name: Sphinx docs html build
run-name: documentation is build for ${{ github.actor }}'s pushed code
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ruff linting check has been started by a ${{ github.event_name }} event!"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install project and dependencies
        run: |
          uv sync --python "3.13" --all-extras --dev
      - name: Build html documentation using sphinx
        run: |
          cd docs
          uv run make html
          cd ..
      - name: Archive sphinx html documentation
        uses: actions/upload-artifact@v4
        with:
          name: html-documentation
          path: docs/build/html
